#!/bin/bash
#
# script/build: Completes and necessary build steps
#

set -e

cd "$(dirname "$0")/.."

echo "==> Building nginx image..."
cd nginx
docker pull debian:bullseye-slim
docker build -t pb-nginx:latest .
cd ..

echo "==> Pulling latest Puppetboard image..."
docker pull ghcr.io/voxpupuli/puppetboard

