#!/bin/bash
#
# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

echo "==> Removing any existing SSL certificates and keys."
rm -fr ./ssl

echo "==> Removing web root directory and any contents."
rm -fr ./web

echo "==> Removing default htpasswd file."
rm -f ./conf/htpasswd

script/bootstrap

echo "==> Set-up completed."
